name: ollang_recipes
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  get_it: ^7.2.0
  provider: ^6.0.2
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  hive: ^2.0.5
  share_plus: 6.3.1
  google_fonts: ^4.0.3
  sizer: ^2.0.15
  kenburns_nullsafety: ^1.0.0

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#ffffff"
  image: assets/images/splash.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/gifs/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
